# Generated by Django 5.0.4 on 2024-05-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_users_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_id',
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='username', max_length=100, primary_key=True, serialize=False),
        ),
    ]
